spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/carrental_prod
    username: root
    password: prod
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  security:
    user:
      name: prod
      password: prod
      roles: ADMIN
  mvc:
    throw-exception-if-no-handler-found: false
  messages:
    basename: messages

server:
  error:
    include-message: always
    include-binding-errors: always